# Generated by Django 5.0.2 on 2024-02-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.PositiveSmallIntegerField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('description', models.TextField(max_length=3000)),
                ('baked_at', models.DateTimeField(auto_now_add=True)),
                ('stock_amount', models.PositiveSmallIntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
            ],
        ),
    ]
