# Generated by Django 5.0.1 on 2024-02-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='cake',
            name='weight',
            field=models.FloatField(default=0, help_text='in kqs', verbose_name='çəki'),
        ),
    ]
